services:
  postgres:
    container_name: postgres.tarotcrew.com
    image: postgres:18
    ports:
      - "5552:5432"
    environment:
      - POSTGRES_DB=tarot_data
      - POSTGRES_USER=tarot_user
      - POSTGRES_PASSWORD=tarot1
